### ISSUE TITLE
USER STORY 1.1: User registration

### ISSUE THREAD

**Issue by Stephen-J-Whitaker** [Stephen-J-Whitaker/music-aid#1]
# As a Site User I can register on the website and create an account so that I can log into the website and use it.

## Tasks

- [x] Install Django, gunicorn, dj_database_url and psycopg2
- [x] Create Music Aid project and Songbook app
- [x] Set up cloudinary and elephant SQL
- [x] Deploy to Heroku
- [x] Code header and footer in base.html view and templates
- [x] Code landing page view and templates
- [x] Code navigation view and templates
- [x] Install allauth
- [x] Configure allauth and Django for user / Admin registration as necessary
- [x] Style the new front end features
- [x] Test the new functionality

## Acceptance Criteria
1	The user can register an account on the website
2	The following acceptance criteria for feature id 1 'Landing Page' have been satisfied
2.1	The landing page has a navigation menu
2.2	The landing page has a header that is fixed to the top of the page.
2.3	The landing page has a footer that is fixed to the top of the page.
2.4	The landing page has a navigation menu
2.5	The header and the footer have the company name and application name displayed.
2.6	Clicking the company name or application name will take the user to the Landing page
2.7	If logged in, the landing page displays the users songbook
2.8	The landing page is styled correctly for the site.
2.9	The landing page is responsive and resizes as necessary on a given screen.
3	The following acceptance criteria for feature id '20' Navigation have been satisfied.
3.1	The navigation menu has a navigation link to the user 'Registration' Page
3.2	The navigation menu has navigation link to the user 'login' Page that is styled correctly for the site
3.3	On successful login, the navigation menu has a logout link in place of the login link.
3.4	On successful Admin login, the navigation menu has an admin page link
3.5	The navigation menu is styled correctly for the site.
3.6	The site is responsive and the navigation menu becomes a 'burger icon' on small screens
4	The following acceptance criteria for feature id 3 'Register'  have been satisfied
4.1	The user registration page has a 'Username' field that is a required field.
4.2	The user registration page has an 'Email' field that is optional.
4.3	The user registration page 'Email' field is validated and an invalid email address cannot be submitted.
4.4	The user registration page has a 'Password' and password confirmation field that are validated and that must match for submission to take place.
4.5	The user registration page has a 'Sign Up' button.
4.6	On successful registration there is a message to the user confirming they are logged in as that user.
4.7	The user registration page is styled correctly for the site.
4.8	The user registration page is responsive and resizes as necessary on a given screen.
