### ISSUE TITLE
USER STORY 1.1: User registration

### ISSUE THREAD

**Issue by Stephen-J-Whitaker** [Stephen-J-Whitaker/music-aid#1]
# As a Site User I can register on the website and create an account so that I can log into the website and use it

## Tasks:
- [ ] Install Django, gunicorn, dj_database_url and psycopg2
- [ ] Create Music Aid project and Songbook app
- [ ] Set up cloudinary and elephant SQL
- [ ] Deploy to Heroku
- [ ] Code header and footer in base.html view and templates
- [ ] Code landing page view and templates
- [ ] Code navigation view and templates
- [ ] Install allauth
- [ ] Configure allauth and Django for user / Admin registration as necessary
- [ ] Style the new front end features
- [ ] Test the new functionality

## Acceptance Criteria:
- [ ] The user can register an account on the website
- [ ] The following acceptance criteria for feature id 1 'Landing Page' have been satisfied
- [ ] The landing page has a navigation menu
- [ ] The landing page has a header that is fixed to the top of the page.
- [ ] The landing page has a footer that is fixed to the top of the page.
- [ ] The landing page has a navigation menu
- [ ] The header and the footer have the company name and application name displayed.
- [ ] Clicking the company name or application name will take the user to the Landing page
- [ ] If logged in, the landing page displays the users songbook
- [ ] The landing page is styled correctly for the site.
- [ ] The landing page is responsive and resizes as necessary on a given screen.
- [ ] The following acceptance criteria for feature id '20' Navigation have been satisfied.
- [ ] The navigation menu has a navigation link to the user 'Registration' Page
- [ ] The navigation menu has navigation link to the user 'login' Page that is styled correctly for the site
- [ ] On successful login, the navigation menu has a logout link in place of the login link.
- [ ] On successful Admin login, the navigation menu has an admin page link
- [ ] The navigation menu is styled correctly for the site.
- [ ] The site is responsive and the navigation menu becomes a 'burger icon' on small screens
- [ ] The following acceptance criteria for feature id 3 'Register'  have been satisfied
- [ ] The user registration page has a 'Username' field that is a required field.
- [ ] The user registration page has an 'Email' field that is optional.
- [ ] The user registration page 'Email' field is validated and an invalid email address cannot be submitted.
- [ ] The user registration page has a 'Password' and password confirmation field that are validated and that must match for submission to take place.
- [ ] The user registration page has a submit button.
- [ ] On successful registration there is a message to the user confirming they are logged in as that user.
- [ ] The user registration page is styled correctly for the site.
- [ ] The user registration page is responsive and resizes as necessary on a given screen.
