### ISSUE TITLE
USER STORY 2.6: Administer a song

### ISSUE THREAD

**Issue by Stephen-J-Whitaker** [Stephen-J-Whitaker/music-aid#10]
# As a Site Admin I can add, view, edit and delete songs of any user should corrective administrative action be necessary.

## Tasks

- [x] Configure admin for song administration
- [x] Configure the admin page song edit page to use summernote for lyric create, view, edit and delete functions
- [x] Test the new admin features

## Acceptance Criteria
1	A logged in Site Admin can add, view, edit and delete songs of any user should corrective administrative action be necessary.
2	The following acceptance criteria for feature id '4'  Admin Page have been satisfied.
2.1	There is a song admin section on the site admin page
2.2	All songs are listed on the song admin section of the site admin page
2.3	A site admin can add a song via the song admin section of the site admin page.
2.4	A site admin can select a song from the song list in the song admin section of the admin page and be taken to the admin edit song section of the site admin page.
2.5	A site admin can view a song and all its associated data on the admin edit song section of the admin page.
2.6	A site admin can edit a song and all its associated data on the admin edit song section of the admin page.
2.7	A site admin can select multiple songs from the song list in the song section of the site admin page and delete them
2.8	On clicking to delete multiple songs, the admin is asked to confirm that they'd like to delete them.
2.9	There is a delete button on the admin edit song section of the site admin page that deletes the selected song and all its associated data.
2.10	The site admin is asked to confirm that they would like to delete the song prior to the song deletion being actioned.
2.11	The site admin clicking that they do not wish to confirm deletion returns them to the previous page.
2.12	All songs belonging to the user are deleted when the associated user is deleted by a site admin via the user section of the site admin page.
2.13	The site admin page is responsive and resizes for the screen on which it is being viewed.
