### ISSUE TITLE
USER STORY 2.7: Autoscroll a song

### ISSUE THREAD

**Issue by Stephen-J-Whitaker** [Stephen-J-Whitaker/music-aid#11]
# As a Site User viewing a song, I can initiate and stop autoscroll at the speed set when adding or editing a song so that I can sing or play along to the lyrics without having to manually scroll them.

## Tasks

- [x] Update the song model to contain a play speed field.
- [x] Update the add / edit song page to enable the setting of a play speed
- [x] Update the song view page template and view as required
- [x] Code the autoscroll functionality in python and JavaScript
- [x] Style the new front end features
- [x] Test the new functionality

## Acceptance Criteria
1	A Site User viewing a song can initiate and stop autoscroll at the speed set when adding or editing a song so that they can sing or play along to the lyrics without having to manually scroll them.
2	The following acceptance criteria for feature id '7'  Add Song have been satisfied.
2.1	The add song page has a play speed field that allows a speed of 1 - 5 to be selected.
3	The following acceptance criteria for feature id '10' Edit song have been satisfied.
3.1	The edit song page has a play speed field that allows a speed of 1 - 5 to be selected.
4	The following acceptance criteria for feature id '9' Song View have been satisfied.
4.1	The song view page has a play button just above the footer.
4.2	There is a label with the user set autoscroll speed that is positioned just above the footer on the song view page.
5	The following acceptance criteria for feature id '13' Autoscroll have been satisfied.
5.1	On click the play button is changed to an 'exit' button.
5.2	On clicking the play button, the lyrics stretch over the header and the footer, the exit button is displayed at the bottom of the page and autoscroll initiates.
5.3	The user is returned to the song view page if the 'exit' button is pressed during autoscroll
5.4	On the bottom of the lyrics being reached during autoscroll, the page waits until the user presses 'exit' button. (This is in case the musician is playing to the lyrics that are still displayed). When the user presses the exit button, the lyrics reduce in size revealing the site header footer.
