### ISSUE TITLE
USER STORY 3.1: Add a set of songs

### ISSUE THREAD

**Issue by Stephen-J-Whitaker** [Stephen-J-Whitaker/music-aid#12]
# As a Site User I can add a set title and then select the songs I would like as part of that set.

## Tasks

- [x] Update database schema to contain set name, songs in set, slug and artist
- [x] Update the setlist list page template and view as necessary
- [x] Code the add setlist view, template and urls
- [x] Style the new front end features
- [x] Test the new functionality

## Acceptance Criteria
1	A Site User can add a set title and then select the songs they would like as part of that set.
2	The following acceptance criteria for feature id '14'  Setlist List have been satisfied.
2.1	The setlist list page has an 'Add' button that navigates to the add setlist page on click.
2.2	The 'Add' button is styled consistently with the rest of the site.
3	The following acceptance criteria for feature id '16'  Add Setlist have been satisfied.
3.1	The add setlist page has the heading 'Setlist' at the top just below the header that is styled consistently with the rest of the site.
3.2	The add setlist page has a set name field that is validated, is required and allows up to 150 characters.
3.3	The add setlist page shows a list of all the songs entered by the user with unchecked checkboxes next to them to enable the user to select the songs desired as part of the new set.
3.4	The add setlist page has a 'save' button that saves the new setlist and returns the user to the setlist list page when clicked.
3.5	The save button is styled consistently with the rest of the site.
3.6	The add setlist page has an 'Exit' button that returns the user to the setlist list page when clicked.
3.7	The exit button is styled consistently with the rest of the site.
3.8	The add setlist page has the regular site header, footer and navigation bar with their regular associated links (as defined in the full landing page (id 1) and navigation (id 20) feature acceptance criteria lists)
3.9	The add setlist page is responsive and resizes for the screen on which it is being viewed.
