### ISSUE TITLE
USER STORY 3.2: View a list of sets

### ISSUE THREAD

**Issue by Stephen-J-Whitaker** [Stephen-J-Whitaker/music-aid#13]
# As a Site User I can view a list of all the sets I’ve created so that I can select the one I want to access.

## Tasks

- [x] Update navigation as required
- [x] Code the setlist list page view, template and urls
- [x] Style the new front end features
- [x] Test the new functionality

## Acceptance Criteria
1	A Site User can view a list of all the sets they've created so that they can select the one they want to access.
2	The following acceptance criteria for feature id '20' Navigation have been satisfied.
2.1	The navigation menu has a link to 'setlist'
2.2	The link to setlist is styled correctly for the site.
3	The following acceptance criteria for feature id '14' Setlist list have been satisfied.
3.1	The setlist list page has the heading 'Setlists' at the top just below the header that is styled consistently with the rest of the site.
3.2	The setlist list page show a list of all the setlists that the user has created.
3.3	The setlist list becomes scrollable should the list become too long to fit on the page.
3.4	The setlist list page is responsive and resizes for the screen on which it is being viewed.
3.5	The view a list of sets page has the regular site header, footer and navigation bar with their regular associated links (as defined in the full landing page (id 1) and navigation (id 20) feature acceptance criteria lists)
