### ISSUE TITLE
USER STORY 3.3: View a set of songs

### ISSUE THREAD

**Issue by Stephen-J-Whitaker** [Stephen-J-Whitaker/music-aid#14]
# As a Site User I can view a list of all the songs in a selected set so I don’t have to look through my entire list of songs for the ones I need at that time.

## Tasks

- [x] Code the setlist song list page template view and urls
- [x] Update the setlist list page so that the setlist names in the list are clickable links to a setlist songlist page
- [x] Style the new front end features
- [x] Test the new functionality

## Acceptance Criteria
1	A Site User can view a list of all the songs in a selected set so they don’t have to look through their entire list of songs for the ones they need at that time.
2	Deletion of a song that is linked to a set or sets does not cause an error when trying to view a set of songs that used to contain that song
3	The following acceptance criteria for feature id '14' Setlist list have been satisfied.
3.1	Each set in the setlist list is a clickable link that takes the user to the setlist view page displaying the contents of the clicked set.
4	The following acceptance criteria for feature id '15' Setlist song list have been satisfied.
4.1	The setlist song list page displays the set name just below the header and it is styled consistently with the rest of the site.
4.2	The setlist song list page displays a list of all the songs selected to be part of that set
4.3	The setlist list page has a 'Setlists' button at the bottom just above the footer that returns the user to the list of sets page when clicked. The button is styled consistently with the rest of the site.
4.4	The view a set of songs page has the regular site header, footer and navigation bar with their regular associated links (as defined in the full landing page (id 1) and navigation (id 20) feature acceptance criteria lists)
4.5	The setlist song list page is responsive and resizes for the screen on which it is being viewed.
