### ISSUE TITLE
USER STORY 3.4: View a song from a set

### ISSUE THREAD

**Issue by Stephen-J-Whitaker** [Stephen-J-Whitaker/music-aid#15]
# As a Site User I can view a song from a set and its associated details so that I can make reference to them as required.

## Tasks

- [x] Update song view template and views so that it can also be used for setlist song view
- [x] Update setlist song list so that each song in the list is a clickable link to the setlist song view page for the clicked song
- [x] Style the new front end features
- [x] Test the new functionality

## Acceptance Criteria
1	A Site User can view a song from a set and its associated details so that they can make reference to them as required.
2	The following acceptance criteria for feature id '15' Setlist song list have been satisfied.
2.1	Each song in the setlist song list is a clickable link that takes the user to the setlist song view page displaying the contents of the clicked song.
3	The following acceptance criteria for feature id '21' Setlist Song View have been satisfied.
3.1	The setlist view song page shows the title of the song above the lyrics.
3.2	If the artist for the song was entered by the user it is displayed below the song title.
3.3	The setlist song view page displays the lyrics for the selected song.
3.4	The lyrics on the setlist song view page become scrollable if the lyrics are too long to fit on the screen.
3.5	The setlist song view page has a 'Setlist' button at the bottom returns the user to the Setlist song list if clicked. 
3.6	The 'Setlist' button is fixed at the bottom of the screen above the footer.
3.7	The setlist song view page has an 'Edit' button at the bottom just above the footer that takes the user to the Edit song page when clicked.
3.8	The setlist song view page and all its content are styled correctly for the site.
3.9	The view a song from a set page has the regular site header, footer and navigation bar with their regular associated links (as defined in the full landing page (id 1) and navigation (id 20) feature acceptance criteria lists)
3.10	The setlist song view page is responsive and resizes for the screen on which it is being viewed.
