### ISSUE TITLE
USER STORY 3.5: Edit a Set

### ISSUE THREAD

**Issue by Stephen-J-Whitaker** [Stephen-J-Whitaker/music-aid#16]
# As a Site User I can update a set of songs so I can change the songs in that set as necessary.

## Tasks

- [x] Update the add set page template and view so that it can also be used as the edit set page
- [x] Update the setlist song list page so that it has an edit button at the bottom
- [x] Style the new front end features
- [x] Test the new functionality

## Acceptance Criteria
1	A Site User can update a set of songs so they can change the songs in that set as necessary.
2	The following acceptance criteria for feature id '15' Setlist Song list have been satisfied.
2.1	The setlist song list page has an 'Edit' button at the bottom of the page just above the footer that will take the user to the edit set page when clicked. The 'Edit' button is styled consistently with the rest of the site.
3	The following acceptance criteria for feature id '17' Edit Set have been satisfied.
3.1	The edit setlist page has the heading 'Setlist' at the top just below the header that is styled consistently with the rest of the site.
3.2	The edit setlist page has a set name field that is validated, is required and allows up to 150 characters.
3.3	The edit setlist page shows a list of all the songs entered by the user with checkboxes next to them to enable the user to select the songs desired as part of the set. The checkboxes are pre ticked with songs currently in the set.
3.4	The edit setlist page has a 'save' button that saves the new setlist and returns the user to the setlist list page when clicked.
3.5	The save button is styled consistently with the rest of the site.
3.6	The edit a set page has the regular site header, footer and navigation bar with their regular associated links (as defined in the full landing page (id 1) and navigation (id 20) feature acceptance criteria lists)
3.7	The edit setlist page is responsive and resizes for the screen on which it is being viewed.
