### ISSUE TITLE
USER STORY 3.6: Delete a set

### ISSUE THREAD

**Issue by Stephen-J-Whitaker** [Stephen-J-Whitaker/music-aid#17]
# As a Site User I can delete a set of songs so it can no longer be accessed.

## Tasks

- [x] Code the delete set functionality
- [x] Update the edit set page so that it has a delete button
- [x] Style the new front end features
- [x] Test the new functionality

## Acceptance Criteria
1	A Site User can delete a set of songs so it can no longer be accessed.
2	The following acceptance criteria for feature id '17' Edit Set have been satisfied.
2.1	The edit setlist page has a 'Delete' button styled consistently with the rest of the site.
3	The following acceptance criteria for feature id '18' Delete Set have been satisfied.
3.1	The user is asked to confirm that they wish to delete the selected set.
3.2	If the user states that they do not wish to delete the selected set, they are returned to the edit set page.
3.3	 On confirming that deletion is required, the deletion takes place and user is returned to the setlist list page.
