### ISSUE TITLE
USER STORY 1.2: User Sign In

### ISSUE THREAD

**Issue by Stephen-J-Whitaker** [Stephen-J-Whitaker/music-aid#2]
# As a Site User I can sign into the website so that I can use it.

## Tasks

- [x] Configure allauth and Django for user / Admin sign in as necessary
- [x] Style the new front end features
- [x] Test the new functionality

## Acceptance Criteria
1	The site user / admin can sign into the website with their previously registered credentials.
2	The following acceptance criteria for feature id 2 'Sign In' have been satisfied.
2.1	The 'Login' page has a link to the user registration page (for use in the even a user has not yet registered)
2.2	The 'Login' page has a username field that is a required field required.
2.3	The 'Login' page has a password field that is required field.
2.4	On successful sign in the user is notified that they have successfully signed in.
2.5	The login page is styled correctly for the site.
2.6	The login page is responsive and resizes for the screen on which it is being viewed.
