### ISSUE TITLE
USER STORY 1.3: User Sign Out

### ISSUE THREAD

**Issue by Stephen-J-Whitaker** [Stephen-J-Whitaker/music-aid#3]
# As a Site User /Admin I can sign out of the website so that others cannot access my account from the device I have been using.

## Tasks

- [x] Configure allauth and Django for user / Admin sign out as necessary
- [x] Style the new front end features
- [x] Test the new functionality

## Acceptance Criteria
1	The user can sign out of the website
2	The following acceptance criteria for feature id 6 'Sign Out' have been satisfied
2.1	On successful sign out, the user is notified that they have successfully signed out.
2.2	On clicking sign out, the user is asked to confirm that they'd like to sign out.
2.3	On successful logout the user is returned to the landing page.
