### ISSUE TITLE
USER STORY 2.1: Add a songs lyrics

### ISSUE THREAD

**Issue by Stephen-J-Whitaker** [Stephen-J-Whitaker/music-aid#5]
# As a Site User I can add a songs title and lyrics and autoscroll speed and optionally the songs artist to my songbook so that I can view them later.

## Tasks

- [x] Install summernote
- [x] Update the songbook list page with add button
- [x] Code the add song page view and templates
- [x] Configure summernote to have no toolbar and be used to enter text into the lyrics field.
- [x] Style the new front end features
- [x] Test the new functionality

## Acceptance Criteria
1	The site user can add a songs title and lyrics and autoscroll speed and optionally the songs artist to their songbook so that they can view them later.
2	The following acceptance criteria for feature id '8' Songbook list have been satisfied.
2.1	The songbook list page has an 'add' button that navigates to the add song page.
2.2	The add button is styled consistently with the rest of the site.
3	The following acceptance criteria for feature id '7'  Add Song have been satisfied.
3.1	The add song page has the heading 'Song' just below the header that is styled consistently with the rest of the site.
3.2	The add song page has a title field that is validated, is required and allows up to 150 characters.
3.3	The add song page has an artist field that is validated, is optional and allows up to 150 characters.
3.4	The add song page has a text box lyrics field that allows for characters to be entered.
3.5	The add song page has a save button that saves the user entered data
3.6	The add song page has an exit button that returns the user to the songbook page.
3.7	The add song page has the regular site header, footer and navigation bar with their regular associated links (as defined in the full landing page (id 1) and navigation (id 20) feature acceptance criteria lists)
3.8	The add song page is styled correctly for the site.
3.9	The add song page is responsive and resizes for the screen on which it is being viewed.
