### ISSUE TITLE
USER STORY 2.2: View a list of songs

### ISSUE THREAD

**Issue by Stephen-J-Whitaker** [Stephen-J-Whitaker/music-aid#6]
# As a Site User I can view a list of all the songs I’ve entered so I can make a selection.

## Tasks

- [x] Update the navigation menu
- [x] Add song table to database model with title, artist, lyrics, user link and slug fields.
- [x] Code the songbook list page view and templates
- [x] Style the new front end features
- [x] Test the songbook list page

## Acceptance Criteria
1	The site user can view a list of songs that they have entered.
2	The following acceptance criteria for feature id '20' Navigation have been satisfied.
2.1	The navigation menu has a link to the 'Songbook' page that is styled correctly for the site.
3	The following acceptance criteria for feature id '8' Songbook List have been satisfied.
3.1	The songbook list page has the heading 'Songbook' just below the header.
3.2	The songbook list has an alphabetically ordered list of all the songs that a user has entered.
3.3	The view a list of songs page has the regular site header, footer and navigation bar with their regular associated links (as defined in the full landing page (id 1) and navigation (id 20) feature acceptance criteria lists)
3.4	The songbook list page is responsive and resizes for the screen on which it is being viewed.
3.5	The songbook list becomes scrollable if the list is too long to fit on the page.
