### ISSUE TITLE
USER STORY 2.3: View a song

### ISSUE THREAD

**Issue by Stephen-J-Whitaker** [Stephen-J-Whitaker/music-aid#7]
# As a Site User I can view a song I’ve entered and its associated details so that I can make reference to them as required.

## Tasks

- [x] Update songbook list so that each song is a clickable link to the song ( template and view)
- [x] Code song view page template and view
- [x] Style the new front end features
- [x] Test the new song view functionality

## Acceptance Criteria
1	The user can view a song that they have entered along with all its associated data.
2	The following acceptance criteria for feature id '8' Songbook List have been satisfied.
2.1	Each song on the songbook list is a clickable link that takes the user to the songs view song page.
3	The following acceptance criteria for feature id '9' Song View have been satisfied.
3.1	The view song page shows the title of the song above the lyrics.
3.2	If the artist for the song was entered by the user it is displayed below the song title.
3.3	The song view page displays the lyrics for the selected song.
3.4	The lyrics on the song view page become scrollable if the lyrics are too long to fit on the screen.
3.5	The song view page has a 'songbook' button at the bottom that returns the user to the songbook list if clicked. 
3.6	The 'songbook' button is fixed at the bottom of the screen above the footer.
3.7	The song view page and all its content are styled correctly for the site.
3.8	The view a song page has the regular site header, footer and navigation bar with their regular associated links (as defined in the full landing page (id 1) and navigation (id 20) feature acceptance criteria lists)
3.9	The song view page is responsive and resizes for the screen on which it is being viewed.
