### ISSUE TITLE
USER STORY 2.4: Edit a song

### ISSUE THREAD

**Issue by Stephen-J-Whitaker** [Stephen-J-Whitaker/music-aid#8]
#  As a Site User I can update a song I’ve entered so I can alter details as necessary.

## Tasks

- [x] Update the song view page view and template as necessary
- [x] Update the add song page view and template and urls so reusable as song edit page
- [x] Style the new front end features
- [x] Test all new features

## Acceptance Criteria
1	The user can edit a song that they have entered.
2	The following acceptance criteria for feature id '9' Song View have been satisfied.
2.1	There is an 'Edit' button on the song view page, that takes the user to the song edit page on click.
3	The following acceptance criteria for feature id '10' Edit song have been satisfied.
3.1	The edit page has the heading 'Song' just below the header.
3.2	The edit song page has a title field that is validated and allows up to 150 characters.
3.3	The edit song page has an artist field that is validated and allows up to 150 characters.
3.4	The edit song page has a text box lyrics field that allows for characters to be entered.
3.5	The edit song page has a save button that saves the user entered data then returns the user to the songbook list page
3.6	The edit song page has the regular site header, footer and navigation bar with their regular associated links (as defined in the full feature acceptance criteria list)
3.7	The edit song page is styled correctly for the site.
3.8	The edit song page is responsive and resizes for the screen on which it is being viewed.
3.9	The edit song page has the regular site header, footer and navigation bar with their regular associated links (as defined in the full landing page (id 1) and navigation (id 20) feature acceptance criteria lists)
