### ISSUE TITLE
USER STORY 2.5: Delete a song

### ISSUE THREAD

**Issue by Stephen-J-Whitaker** [Stephen-J-Whitaker/music-aid#9]
# As a Site User I can delete a song I’ve entered from songbook so it can no longer be accessed.

## Tasks

- [x] Update the add song template to show a 'delete' button in place of the 'exit' button.
- [x] Code so that clicking delete button works as specified
- [x] Style the new front end features
- [x] Test new functionality

## Acceptance Criteria
1	The user can delete a song that they have entered.
2	The following acceptance criteria for feature id '10' Edit song have been satisfied.
2.1	The edit song page has a delete button that deletes the song currently shown in the edit song page and is styled consistently with the rest of the site.
3	The following acceptance criteria for feature id '11' Delete song have been satisfied.
3.1	On pressing the delete button, the user is asked to confirm that they wish to delete the song.
3.2	If the user states that they do not wish to delete the selected song, they are returned to the edit song page.
3.3	On successful deletion of the selected song, the user is redirected to the songbook list page.
3.4	The site user clicking that they do not wish to confirm deletion returns them to the previous page.
